/**
 * TypeScript client for the escrow program — deposit / release / refund.
 *
 * This is how the agent flow would use escrow instead of a direct transfer: the buyer **deposits**
 * for an order keyed by its Solana Pay `reference`; the seller is paid only when the buyer
 * **releases** (after delivery); the buyer can **refund** after the deadline. The `reference` is the
 * exact same key the seller already mints per request — so escrow drops into the existing protocol.
 *
 * Requires `anchor build` first (generates `../target/types/escrow.ts` + the IDL).
 */
import * as anchor from '@coral-xyz/anchor'
import { Program, BN } from '@coral-xyz/anchor'
import { PublicKey, Keypair, LAMPORTS_PER_SOL } from '@solana/web3.js'
// import type { Escrow } from '../target/types/escrow'   // generated by `anchor build`

// Deployed to devnet (anchor deploy). Run `anchor keys sync` after a fresh build to set your own.
export const PROGRAM_ID = new PublicKey('R5NWNg9eRLWWQU81Xbzz5Du1k7jTDeeT92Ty6qCeXet')

/** Derive the per-order escrow PDA: one per (buyer, reference). */
export function escrowPda(buyer: PublicKey, reference: PublicKey): PublicKey {
  return PublicKey.findProgramAddressSync(
    [Buffer.from('escrow'), buyer.toBuffer(), reference.toBuffer()],
    PROGRAM_ID,
  )[0]
}

/** Buyer deposits `amountSol` for `reference`, refundable `deadlineSecs` from now. */
export async function deposit(
  program: Program<any>,
  buyer: Keypair,
  seller: PublicKey,
  reference: PublicKey,
  amountSol: number,
  deadlineSecs: number,
): Promise<string> {
  const deadline = new BN(Math.floor(Date.now() / 1000) + deadlineSecs)
  return program.methods
    .initialize(new BN(Math.round(amountSol * LAMPORTS_PER_SOL)), reference, deadline)
    .accounts({ buyer: buyer.publicKey, seller, escrow: escrowPda(buyer.publicKey, reference) })
    .signers([buyer])
    .rpc()
}

/** Buyer confirms delivery → pay the seller and close the escrow. */
export async function release(
  program: Program<any>,
  buyer: Keypair,
  seller: PublicKey,
  reference: PublicKey,
): Promise<string> {
  return program.methods
    .release()
    .accounts({ buyer: buyer.publicKey, seller, escrow: escrowPda(buyer.publicKey, reference) })
    .signers([buyer])
    .rpc()
}

/**
 * Seller-side check: does a funded escrow exist for `(buyer, reference)` naming `seller`, holding at
 * least `minAmountSol`? The seller calls this before delivering — "is there money locked for me?" —
 * replacing the direct-transfer `verifyPayment` in the escrow settlement path. Returns false if the
 * PDA doesn't exist, the parties don't match, or it's underfunded.
 */
export async function isFunded(
  program: Program<any>,
  buyer: PublicKey,
  seller: PublicKey,
  reference: PublicKey,
  minAmountSol = 0,
): Promise<boolean> {
  const acct = await program.account.escrow.fetchNullable(escrowPda(buyer, reference))
  if (!acct) return false
  const partiesOk = acct.buyer.equals(buyer) && acct.seller.equals(seller)
  const amountOk = acct.amount.toNumber() >= Math.round(minAmountSol * LAMPORTS_PER_SOL)
  return partiesOk && amountOk
}

/** Buyer reclaims the deposit after the deadline (seller never delivered). */
export async function refund(
  program: Program<any>,
  buyer: Keypair,
  reference: PublicKey,
): Promise<string> {
  return program.methods
    .refund()
    .accounts({ buyer: buyer.publicKey, escrow: escrowPda(buyer.publicKey, reference) })
    .signers([buyer])
    .rpc()
}
